
# pipeline configuration: note that if an entry is missing, the corresponding interface
# will be instantiated instead (if possible).
pipeline:
  # modules beginning with "." are relative to this base package
  _base_package: swisstext.cmd.scraping.tools

  # default tools to use
  crawler: .JustextCrawler
  normalizer: .Normalizer
  splitter: .MocySplitter
  sentence_filter: .PatternSentenceFilter
  sg_detector: .SwigspotLangid # swisstext.mclid.TfLangidGsw
  decider: .OneNewSgDecider
  saver: .MongoSaver
  seed_creator: .IdfSeedCreator

# special options to pass to the tools constructors
crawler_options:
  keep_bad: false # ignore sentences labelled as 'bad' or 'short' by justext

normalizer_options:
  fix_encoding: true
  strip_emojis: true

splitter_options:
  more: true  # split on :;
  keep_newlines: true # trust justext segmentation

# global options
options:
  min_proba: 0.85   # minimum Swiss German probability (inclusive) to keep a sentence
  crawl_depth: 2    # maximal recursion during scraping (inclusive)
  num_workers: 1    # maximum number of threads to use during scraping

# options for the saver. Currently, this is mandatory for the whole command line tool to work...
# in case you use something else than the mongo saver, for example the ConsoleSaver, just add the
# options BUT DON'T REMOVE the host, port, db.
# Also, if you code a new saver, ensure its constructors defines a **kwargs argument...
saver_options:
  host: localhost
  port: 27017
  db: swisstext

# Options for the decider: don't crawl child URLs if less than 20% of sentences are Swiss German.
decider_options:
  min_ratio: 0.2