options:
  max_results: 10

search_engine:
  _base_package: swisstext.cmd.searching.tools

  searcher: .StartPageGeneratorFactory
  saver: .MongoSaver

saver_options:
  host: localhost
  port: 27017
  db: swisstext