
pipeline:
  _base_package: swisstext.scraping.tools

  crawler: .bs_crawler.BsCrawler
  splitter: .punkt_splitter.PunktSplitter
  #sentence_filter: .pattern_sentence_filter.PatternSentenceFilter
  sg_detector: .swigspot_langid.SwigspotLangid
  decider: .basic_decider.BasicDecider
  page_saver:  .console_saver.ConsoleSaver # .mongo_saver.MongoSaver
  seed_creator: .basic_seed_creator.BasicSeedCreator

options:
  min_proba: 0.85
  crawl_depth: 2
  num_workers: 1

saver_options:
  host: localhost
  port: 27017
  db: tmp