options:
  max_results: 10
  force_x_new: 0

search_engine:
  _base_package: swisstext.cmd.searching.tools

  searcher: .start_page.StartPageGeneratorFactory
  saver: .mongo_saver.MongoSaver

saver_options:
  host: localhost
  port: 27017
  db: swisstext